#!/usr/bin/env bash

dir="$HOME/.strap"
rm -rf "$dir"
mkdir -p "$dir"
file="$dir/strap.sh"
curl -fsSL https://raw.githubusercontent.com/les-okta/mac/master/strap.sh -o "$file"
[ -f "$file" ] && bash "$file"
rm -rf "$file"
